### ISSUE TITLE
Missing declaration of MultVector

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/meataxe64#17]
Tests of meataxe64 fail - see e.g. in https://travis-ci.org/gap-packages/gap-docker-pkg-tests-stable-4.10-devel/jobs/447062588 

    Error, Variable: 'MultVector' must have a value

Is this because GAP tries to install a method at https://github.com/gap-packages/meataxe64/blob/1d2bd07f1661411fd6fbc73a14aad6c468e1b1c0/gap/vecobj.gi#L155 but can not find its declaration?

**Comment by markuspf** [comment]
`MultVector` doesn't exist in `stable-4.10`, see https://github.com/gap-system/gap/commit/4040d9bbb230ffd9de816461b69b7778f76dfaec

**Comment by olexandr-konovalov** [comment]
OK, then you may wish to update dependencies in https://github.com/gap-packages/meataxe64/blob/1d2bd07f1661411fd6fbc73a14aad6c468e1b1c0/PackageInfo.g#L89 at some point.

**Comment by stevelinton** [comment]
Changed dependencies. There is no nice way to handle an Operation going obsolete, it seems
