### ISSUE TITLE
problem with MTX64_Spin calling MTX64_Echelize

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/meataxe64#23]
The following happens with the current version.
```
gap> MTX64_Spin(n64,[m64,m64]);
Error, Function: number of arguments must be 1 (not 2) in
  MTX64_Echelize( MTX64_NewMatrix( f, 0, n ), rec(
    cleanerNeeded := false ) 
 ) at /.../gap-master/gap/pkg/meataxe64/gap/spin.gi:56 called from 
<function "MTX64_Spin">( <arguments> )
 called from read-eval loop at *stdin*:9
type 'quit;' to quit to outer loop
```
Apparently `MTX_Echelize` expects only one argument.

**Comment by stevelinton** [comment]
The spin code was really just me playing around. I have no idea if it works. The second argument to `Echelize` was an options record that meant something to the GAP recursive echelize, but is not used by the C one.  Eventually there will be C variants that do the various parts of the work.

In the meantime I've pushed a fix for this, but I have no idea if the Spin code is correct.

**Comment by ThomasBreuer** [comment]
@stevelinton Thanks for the fix.
