### ISSUE TITLE
Making a release

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/meataxe64#26]
@stevelinton Travis tests pass here and under the master branch (https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/575631055), website https://gap-packages.github.io/meataxe64/ is set up - shall we make a release? Tests fail under stable-4.10 branch though, so it will be compatible only with coming 4.11.

**Comment by stevelinton** [comment]
We could do. I would not propose it for redistribution with GAP yet, though, and I would need to add appropriate caveats to the release announcement. Richard and I have plans for a significant refactoring which would establish a cleaner interface between the GAP and C parts and provide parallel in-memory versions of key operations.

**Comment by olexandr-konovalov** [comment]
If you are happy with #27, I will be able to publish it (version 0.1 of today?)

**Comment by olexandr-konovalov** [comment]
Version 0.1 of today is now available at https://gap-packages.github.io/meataxe64/
